### ISSUE TITLE
Error building the client. Could not compile ntapi

### ISSUE THREAD

**Issue by aggnostos** [darkarp/chromepass#52]
An error occurred while building the client. Although server was built successfully.

```
error[E0793]: reference to packed field is unaligned
--> C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.6\src\ntexapi.rs:2785:52
|
2785 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
|                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
--> C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.6\src\ntexapi.rs:2809:25
|
2809 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
[-] Client couldn't be copied: [Errno 2] No such file or directory: 'templates/chromepass-build/target/release/chromepass.exe'
[-] Error building the client
```

**Comment by QYH2MMT4EVER** [comment]
Have you solved this problem? I am  stuck  in the same problem!  Could you plz give me some help  to fix up this problem?

**Comment by QYH2MMT4EVER** [comment]
@Lian39

**Comment by darkarp** [comment]
I will look into this issue

**Comment by aggnostos** [comment]
@QYH2MMT4EVER No

**Comment by SHarksGANG** [comment]
**### Hi ! How to fix it ?**

  Compiling solana-frozen-abi-macro v1.14.12
error[E0793]: reference to packed field is unaligned
    --> C:\Users\Arcturus\.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.7\src\ntexapi.rs:2783:52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\Arcturus\.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.7\src\ntexapi.rs:2807:25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

   Compiling miow v0.3.7
For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spl-token-cli v2.4.0`, intermediate artifacts can be found at `C:\Users\Arcturus\AppData\Local\Temp\cargo-installNHDEtX`

C:\Windows\System32>cargo -V
cargo 1.69.0 (6e9a83356 2023-04-12)

C:\Windows\System32>

**Comment by yuezhao238** [comment]
ntapi v0.4.1 code may help :)  https://github.com/MSxDOS/ntapi/blob/master/src/ntexapi.rs

**Comment by SHarksGANG** [comment]
> Код NTAPI v0.4.1 может помочь :) https://github.com/MSxDOS/ntapi/blob/master/src/ntexapi.rs

Thank you very much! I'll test it

**Comment by guanaug** [comment]
I solved it by the following step:
```
cd templates/chromepass-build/ && cargo update
```

**Comment by codingpeace** [comment]
@guanaug Thank you, it's work.

**Comment by darkarp** [comment]
Thanks for the report. Working on a reboot for this to update the structure and all the dependencies. It will all get fixed in the next version with more optional AV/EDR evasion too.

**Comment by noe8xc** [comment]
Hi, I have the same error, I have done the update
cd templates/chromepass-build/ && cargo update 
but I still have the same error, in my case compiling ntapi v0.3.7

[+] Building Client
Compiling chromepass v4.1.5 (C:\Temp\chromepass\templates\chromepass-build)
Compiling ntapi v0.3.7
error[E0793]: reference to packed field is unaligned
--> C:\Users\a\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2783:52
|
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
|                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
= note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
--> C:\Users\a\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2807:25
|
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
= note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` (lib) due to 2 previous errors
[-] Client couldn't be copied: [Errno 2] No such file or directory: 'templates/chromepass-build/target/release/chromepass.exe'
[-] Error building the client

**Comment by wDona** [comment]
This error keeps happening

DEBUG:root:error[E0793]: reference to packed field is unaligned
DEBUG:root:--> C:\Users\donan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.6\src\ntexapi.rs:2785:52
DEBUG:root:|
DEBUG:root:2785 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
DEBUG:root:|                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG:root:|
DEBUG:root:= note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
DEBUG:root:= note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
DEBUG:root:= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)
DEBUG:root:
DEBUG:root:error[E0793]: reference to packed field is unaligned
DEBUG:root:--> C:\Users\donan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.6\src\ntexapi.rs:2809:25
DEBUG:root:|
DEBUG:root:2809 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
DEBUG:root:|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG:root:|
DEBUG:root:= note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
DEBUG:root:= note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
DEBUG:root:= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)
DEBUG:root:
DEBUG:root:For more information about this error, try `rustc --explain E0793`.
DEBUG:root:error: could not compile `ntapi` (lib) due to 2 previous errors
DEBUG:root:warning: build failed, waiting for other jobs to finish...

**Comment by wis610** [comment]
Hello, I am getting same error, anyone can u help me to resolve this error?

error[E0793]: reference to packed field is unaligned
    --> C:\Users\nisha\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2783:52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses    
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\nisha\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2807:25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses    
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

   Compiling number_prefix v0.4.0                                                                                            
For more information about this error, try `rustc --explain E0793`.                                                          
error: could not compile `ntapi` (lib) due to 2 previous errors

**Comment by Siradankullanici** [comment]
Update one of that dependencies. For example sysinfo.
